apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aeya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aeya
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aeya
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aeya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aeya
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ofnu-tenant/rhtap-demo-app/hacbs-test-project-aeya@sha256:4c73ffe1819a96e0e1a90d63397925b53d2b4b42263364b5b18466c7887bdd7d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
